apiVersion: v1
kind: Service
metadata:
  name: diabetic-api-service
  labels:
    app: diabetic-api
spec:
  type: ClusterIP
  selector:
    app: diabetic-api
  ports:
    - name: http
      port: 80
      targetPort: http
